function res=run_scenarios(...
    location,...
    runs,...
    X,...
    ptpars,...
    prm,...
    ref,...
    sel,...
    agg,...
    gps,...
    hivpoints,...
    SFIN,...
    ptbds,...
    pt_type)


id=prm.id;

top=size(X,1);

effyear=2;

% Optimal regimen
[~, iii]=sort(runs.effs(2:end,effyear));
lhs_opt=runs.grid(iii(end),:);
lhs_opt(2) = ptbds(2,1);
lhs_opt([4,5,6])=ptbds([4,5,6],2);


% Min regimen
[~, g]=(min((runs.effs(2:end,effyear)-0.70).^2));
if(numel(g)>1)
    g=g(1);
end
lhs_min=runs.grid(g,:);
lhs_min(2) = ptbds(2,2);
lhs_min([4,5,6])=ptbds([4,5,6],1);

lhs_base=[...
    prm.r.ptdur,...
    prm.r.ptregdur,...
    prm.p.pteffi,...
    prm.p.ptdrbarrier,...
    prm.p.ptforg,...
    prm.p.ptcomp,...
    prm.p.potency];


% lhs_base=runs.grid_base;


nohh=[ptpars(1) ptpars(2) 0 ];
% hh50=[ptpars(1) ptpars(2) ptpars(3)*0.5];
expand=ptpars;


%memory allocation
[inc ,inc_mdr, mrt , mrt_n, inc_tbhiv, inc_n, inc_tbhivn,pop,ipt_all, ipt_hiv,ipt_nohiv,...
    ]=deal(zeros(top,(prm.endy-2019),7));

%% Uncomment this section only if parallel pools allowed in machine
% p = gcp('nocreate'); % If no pool, do not create new one.
% if isempty(p)
%     
%     ncores=maxNumCompThreads;
%     parpool('local',ncores);
% end
% ppm = ParforProgMon(location, top);
% 
% parfor j=1:top
%     ppm.increment();
%%

for j=1:top
    
    %Progress tracker
     
    perc = 1e2*j/top;
    text = [num2str(perc),'%'];
    
    disp(text)
    
    sfin=SFIN(j,:);
    x=X(j,:);
    statusquo=[x(id) 0 0];
    
    % Baseline parameters
    %
    objlhs     = @(ptpars,lhsbase,lhspars) ...
        get_full_dyn(ptpars,x,lhsbase,lhspars, prm,...
        ref, sel, agg, gps, hivpoints, sfin);
    
    
    run0=objlhs(statusquo,lhs_base,lhs_base);
    run1=objlhs(nohh,lhs_base,lhs_min);
    run2=objlhs(expand,lhs_base,lhs_min);
    run3=objlhs(nohh,lhs_base,lhs_opt);
    run4=objlhs(expand,lhs_base,lhs_opt);
    run5=objlhs(nohh,lhs_base,lhs_base);
    run6=objlhs(expand,lhs_base,lhs_base);
    
    
    inc(j,:,:)         =[...
        run0.inc_all...
        run1.inc_all...
        run2.inc_all...
        run3.inc_all...
        run4.inc_all...
        run5.inc_all...
        run6.inc_all];
    
    inc_mdr(j,:,:)     =[...
        run0.inc_mdr...
        run1.inc_mdr...
        run2.inc_mdr...
        run3.inc_mdr...
        run4.inc_mdr...
        run5.inc_mdr...
        run6.inc_mdr];
    
    mrt(j,:,:)         =[...
        run0.mort_tball'...
        run1.mort_tball'...
        run2.mort_tball'...
        run3.mort_tball'...
        run4.mort_tball'...
        run5.mort_tball'...
        run6.mort_tball'];
    
    inc_tbhiv(j,:,:)   =[...
        run0.inc_tbhiv...
        run1.inc_tbhiv...
        run2.inc_tbhiv...
        run3.inc_tbhiv...
        run4.inc_tbhiv...
        run5.inc_tbhiv...
        run6.inc_tbhiv];
    
    inc_tbhivn(j,:,:)  =[...
        ((run0.inc_tbhiv'.*run0.popu)/1e5)'...
        ((run1.inc_tbhiv'.*run1.popu)/1e5)'...
        ((run2.inc_tbhiv'.*run2.popu)/1e5)'...
        ((run3.inc_tbhiv'.*run3.popu)/1e5)'...
        ((run4.inc_tbhiv'.*run4.popu)/1e5)'...
        ((run5.inc_tbhiv'.*run5.popu)/1e5)'...
        ((run6.inc_tbhiv'.*run6.popu)/1e5)'...
        ];
    
    pop(j,:,:)         =[...
        run0.popu'...
        run1.popu'...
        run2.popu'...
        run3.popu'...
        run4.popu'...
        run5.popu'...  
        run6.popu'...
        ];
    inc_n(j,:,:)       =[...
        ((run0.inc_all'.*run0.popu)/1e5)'...
        ((run1.inc_all'.*run1.popu)/1e5)'...
        ((run2.inc_all'.*run2.popu)/1e5)'...
        ((run3.inc_all'.*run3.popu)/1e5)'...
        ((run4.inc_all'.*run4.popu)/1e5)'...
        ((run5.inc_all'.*run5.popu)/1e5)'...
        ((run6.inc_all'.*run6.popu)/1e5)'... 
         ];
    
    mrt_n(j,:,:)       =[...
        ((run0.mort_tball.*run0.popu)/1e5)'...
        ((run1.mort_tball.*run1.popu)/1e5)'...
        ((run2.mort_tball.*run2.popu)/1e5)'...
        ((run3.mort_tball.*run3.popu)/1e5)'...
        ((run4.mort_tball.*run4.popu)/1e5)'...
         ((run5.mort_tball.*run5.popu)/1e5)'...
         ((run6.mort_tball.*run6.popu)/1e5)'... 
         ];
    
    
    
    ipt_all(j,:,:)     =[...
        run0.ipt_all...
        run1.ipt_all...
        run2.ipt_all...
        run3.ipt_all...
        run4.ipt_all...
        run5.ipt_all...
        run6.ipt_all...
         ];
    ipt_hiv(j,:,:)     =[...
        run0.ipt_hiv...
        run1.ipt_hiv...
        run2.ipt_hiv...
        run3.ipt_hiv...
        run4.ipt_hiv...
        run5.ipt_hiv...
        run6.ipt_hiv...
        ];
    ipt_nohiv(j,:,:)   =[...
        run0.ipt_nohiv...
        run1.ipt_nohiv...
        run2.ipt_nohiv...
        run3.ipt_nohiv...
        run4.ipt_nohiv...
        run5.ipt_nohiv...
        run6.ipt_nohiv...
        ];
    
    
end

% Arrange outputs 

%Cumulative incidence
cuminc=cat(3,...
    cumsum(inc_n(:,:,1),2) ,...
    cumsum(inc_n(:,:,2),2),...
    cumsum(inc_n(:,:,3),2) ,...
    cumsum(inc_n(:,:,4),2),...
    cumsum(inc_n(:,:,5),2),...
    cumsum(inc_n(:,:,6),2),...
    cumsum(inc_n(:,:,7),2)...
    );

%Cumulative mortality

cummrt=cat(3,...
    cumsum(mrt_n(:,:,1),2) ,...
    cumsum(mrt_n(:,:,2),2),...
    cumsum(mrt_n(:,:,3),2) ,...
    cumsum(mrt_n(:,:,4),2),...
    cumsum(mrt_n(:,:,5),2),...
    cumsum(mrt_n(:,:,6),2),...
    cumsum(mrt_n(:,:,7),2)...
    );


cuminc_tbhiv=cat(3,...
    cumsum(inc_tbhivn(:,:,1),2),...
    cumsum(inc_tbhivn(:,:,2),2),...
    cumsum(inc_tbhivn(:,:,3),2),...
    cumsum(inc_tbhivn(:,:,4),2),...
    cumsum(inc_tbhivn(:,:,5),2),...
    cumsum(inc_tbhivn(:,:,6),2),...
    cumsum(inc_tbhivn(:,:,7),2)...
    );

arr        =[...
    (cuminc(:,end,1)-cuminc(:,end,2))./cuminc(:,end,1),...
    (cuminc(:,end,1)-cuminc(:,end,3))./cuminc(:,end,1),...
    (cuminc(:,end,1)-cuminc(:,end,4))./cuminc(:,end,1),...
    (cuminc(:,end,1)-cuminc(:,end,5))./cuminc(:,end,1),...
    (cuminc(:,end,1)-cuminc(:,end,6))./cuminc(:,end,1),...
    (cuminc(:,end,1)-cuminc(:,end,7))./cuminc(:,end,1)...
    ];

arr_mrt        =[...
    (cummrt(:,end,1)-cummrt(:,end,2))./cummrt(:,end,1),...
    (cummrt(:,end,1)-cummrt(:,end,3))./cummrt(:,end,1),...
    (cummrt(:,end,1)-cummrt(:,end,4))./cummrt(:,end,1),...
    (cummrt(:,end,1)-cummrt(:,end,5))./cummrt(:,end,1),...
    (cummrt(:,end,1)-cummrt(:,end,6))./cummrt(:,end,1),...
    (cummrt(:,end,1)-cummrt(:,end,7))./cummrt(:,end,1)...
    ];


arr6H        =[...
    (cuminc(:,end,6)-cuminc(:,end,2))./cuminc(:,end,6),...
    (cuminc(:,end,7)-cuminc(:,end,3))./cuminc(:,end,7),...
    (cuminc(:,end,6)-cuminc(:,end,4))./cuminc(:,end,6),...
    (cuminc(:,end,7)-cuminc(:,end,5))./cuminc(:,end,7),...
    (cuminc(:,end,6)-cuminc(:,end,6))./cuminc(:,end,6),...
    (cuminc(:,end,7)-cuminc(:,end,7))./cuminc(:,end,7)...
    ];

arr6H_mrt        =[...
    (cummrt(:,end,6)-cummrt(:,end,2))./cummrt(:,end,6),...
    (cummrt(:,end,7)-cummrt(:,end,3))./cummrt(:,end,7),...
    (cummrt(:,end,6)-cummrt(:,end,4))./cummrt(:,end,6),...
    (cummrt(:,end,7)-cummrt(:,end,5))./cummrt(:,end,7),...
    (cuminc(:,end,6)-cuminc(:,end,6))./cuminc(:,end,6)...
    (cuminc(:,end,7)-cuminc(:,end,7))./cuminc(:,end,7)...
    ];



nnt        =1./arr;

res.inc=inc;
res.inc_mdr=inc_mdr;
res.mrt=mrt;
res.inc_tbhiv=inc_tbhiv;
res.inc_tbhivn=inc_tbhivn;
res.cuminc_tbhiv=cuminc_tbhiv;
res.pop=pop;
res.inc_n=inc_n;
res.mrt_n=mrt_n;

res.cuminc=cuminc;
res.cummrt=cummrt;
res.ipt_all=ipt_all;
res.ipt_hiv=ipt_hiv;
res.ipt_nohiv=ipt_nohiv;
res.arr=arr;
res.arr_mrt=arr_mrt;
res.arr6H=arr6H;
res.arr6H_mrt=arr6H_mrt;

res.nnt=nnt;
res.opt=lhs_opt;
res.base=lhs_base;
res.min=lhs_min;


save_results(res,'scenarios',location,pt_type);


end